/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Registro;
import javax.swing.JOptionPane;

/**
 *
 * @author Yo
 */
public class EliminarProducto extends javax.swing.JFrame {

    /**
     * Creates new form EliminarProducto
     */
    
    private Registro registro;
    
    ListarProducto listar = new ListarProducto();
    
    public EliminarProducto() {
        
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        this.registro = new Registro();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        idEliminar = new javax.swing.JTextField();
        bottonEliminar = new javax.swing.JButton();
        bottonLimpiar = new javax.swing.JButton();
        textInfo = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Regresar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        agregarM = new javax.swing.JMenuItem();
        modificarM = new javax.swing.JMenuItem();
        listarM = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        idEliminar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idEliminarKeyTyped(evt);
            }
        });
        jPanel1.add(idEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 130, -1));

        bottonEliminar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        bottonEliminar.setForeground(new java.awt.Color(255, 51, 51));
        bottonEliminar.setText("Eliminar Producto");
        bottonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(bottonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, -1));

        bottonLimpiar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        bottonLimpiar.setForeground(new java.awt.Color(102, 102, 102));
        bottonLimpiar.setText("Limpiar Casilla");
        bottonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(bottonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 130, -1));

        textInfo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        textInfo.setForeground(new java.awt.Color(255, 255, 255));
        textInfo.setText("ID de producto a eliminar");
        jPanel1.add(textInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoMetodos.png"))); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 400));

        jMenu1.setText("Inicio");

        Regresar.setText("Regresar");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });
        jMenu1.add(Regresar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Usuario");

        agregarM.setText("Agregar Productos");
        agregarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarMActionPerformed(evt);
            }
        });
        jMenu2.add(agregarM);

        modificarM.setText("Modificar Productos");
        modificarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarMActionPerformed(evt);
            }
        });
        jMenu2.add(modificarM);

        listarM.setText("Listar Productos");
        listarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarMActionPerformed(evt);
            }
        });
        jMenu2.add(listarM);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idEliminarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idEliminarKeyTyped
        char validar = evt.getKeyChar();

        if(Character.isLetter(validar) || Character.isWhitespace(validar)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_idEliminarKeyTyped

    private void bottonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonEliminarActionPerformed

        String idText = this.idEliminar.getText();
        
       
        
        if(!idText.isEmpty()){
            
            int id = Integer.parseInt(idText);
            
            if(registro.eliminarProducto(id)){
                
                JOptionPane.showMessageDialog(this, "Producto eliminado correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            }else{
                
                JOptionPane.showMessageDialog(this, "El producto con ID: "+id+" no existe, verifica en la lista de productos", "Error", JOptionPane.ERROR_MESSAGE);
                listar.setVisible(true); 
                
            }
        }else{
            JOptionPane.showMessageDialog(this, "Tienes que rellenar la casilla", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_bottonEliminarActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        this.dispose();
        this.idEliminar.setText("");
    }//GEN-LAST:event_RegresarActionPerformed

    private void bottonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonLimpiarActionPerformed
        this.idEliminar.setText("");
    }//GEN-LAST:event_bottonLimpiarActionPerformed

    private void agregarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarMActionPerformed
        AgregarProducto agregarr = new AgregarProducto();
        
        
        agregarr.setVisible(true);
        
        this.dispose();
        
        this.idEliminar.setText("");
        
    }//GEN-LAST:event_agregarMActionPerformed

    private void modificarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarMActionPerformed
        ModificarProducto modificarr = new ModificarProducto();
        
        
        modificarr.setVisible(true);
        
        this.dispose();
        
        this.idEliminar.setText("");
    }//GEN-LAST:event_modificarMActionPerformed

    private void listarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarMActionPerformed
        ListarProducto listarr = new ListarProducto();
        
        
        listarr.setVisible(true);
        
        this.dispose();
        
        this.idEliminar.setText("");
        
    }//GEN-LAST:event_listarMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EliminarProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Regresar;
    private javax.swing.JMenuItem agregarM;
    private javax.swing.JButton bottonEliminar;
    private javax.swing.JButton bottonLimpiar;
    private javax.swing.JLabel fondo;
    private javax.swing.JTextField idEliminar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem listarM;
    private javax.swing.JMenuItem modificarM;
    private javax.swing.JLabel textInfo;
    // End of variables declaration//GEN-END:variables
}
