/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Registro;
import javax.swing.JOptionPane;
import metodo.TextPrompt;

/**
 *
 * @author Yo
 */
public class InicioSesion extends javax.swing.JFrame {

    /**
     * Creates new form InicioSesion
     */
    
    private Registro registro;
    
    MenuPrincipal menu = new MenuPrincipal();
    
    public InicioSesion() {
        initComponents();
        
        this.registro = new Registro();
        
        this.setLocationRelativeTo(null);
        
        TextPrompt nombre = new TextPrompt("Nombre de usuario", this.nombreU);
        TextPrompt contraseña = new TextPrompt("Contraseña", this.contraseñaU);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        TextoInformacion = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        FondoLogeo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        TextoInicioSesion = new javax.swing.JLabel();
        LineaContraseña = new javax.swing.JLabel();
        LineaUsuario = new javax.swing.JLabel();
        nombreU = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        UsuarioLogo = new javax.swing.JLabel();
        ContraseñaLogo = new javax.swing.JLabel();
        contraseñaU = new javax.swing.JPasswordField();
        fondoBlanco1 = new vista.fondoBlanco();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LogoDuoc.png"))); // NOI18N
        jPanel1.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        TextoInformacion.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        TextoInformacion.setText("Sistema Registro de Productos");
        jPanel1.add(TextoInformacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel2.setText("Inicia sesion para continuar");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));

        FondoLogeo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FondoLogeo.jpg"))); // NOI18N
        jPanel1.add(FondoLogeo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 390));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 420, 390));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TextoInicioSesion.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        TextoInicioSesion.setText("Inicio Sesion");
        jPanel2.add(TextoInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        LineaContraseña.setText("________________________");
        jPanel2.add(LineaContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 170, -1));

        LineaUsuario.setText("________________________");
        jPanel2.add(LineaUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 170, -1));

        nombreU.setBorder(null);
        jPanel2.add(nombreU, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 140, -1));

        jButton1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 16)); // NOI18N
        jButton1.setText("Iniciar Sesion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 170, -1));

        UsuarioLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/UsuarioLogo.png"))); // NOI18N
        jPanel2.add(UsuarioLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        ContraseñaLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ContraseñaLogo.png"))); // NOI18N
        jPanel2.add(ContraseñaLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        contraseñaU.setBorder(null);
        contraseñaU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                contraseñaUKeyTyped(evt);
            }
        });
        jPanel2.add(contraseñaU, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 140, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 400, 350));

        javax.swing.GroupLayout fondoBlanco1Layout = new javax.swing.GroupLayout(fondoBlanco1);
        fondoBlanco1.setLayout(fondoBlanco1Layout);
        fondoBlanco1Layout.setHorizontalGroup(
            fondoBlanco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        fondoBlanco1Layout.setVerticalGroup(
            fondoBlanco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        getContentPane().add(fondoBlanco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String nombreUsuario = this.nombreU.getText();
        String contraseñaUsuario =  this.contraseñaU.getText();
        
        if(!nombreUsuario.isEmpty() && !contraseñaUsuario.isEmpty()){
            if (registro.iniciarSesion(nombreUsuario, contraseñaUsuario)) {
                JOptionPane.showMessageDialog(this, "Inicio de sesión exitoso", "Éxito", JOptionPane.INFORMATION_MESSAGE);
     
                this.dispose();
                
                menu.getText(this.nombreU.getText());
                
                menu.setVisible(true);
                
                
            } else {
                JOptionPane.showMessageDialog(this, "Inicio de sesión fallido. Verifica tu nombre de usuario y contraseña.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
        }else{
            JOptionPane.showMessageDialog(this, "Tienes que poner tus datos para ingresar al sistema.", "Error", JOptionPane.ERROR_MESSAGE);
        } 
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void contraseñaUKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contraseñaUKeyTyped
        char validar = evt.getKeyChar();

        if(Character.isWhitespace(validar)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_contraseñaUKeyTyped

    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ContraseñaLogo;
    private javax.swing.JLabel FondoLogeo;
    private javax.swing.JLabel LineaContraseña;
    private javax.swing.JLabel LineaUsuario;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel TextoInformacion;
    private javax.swing.JLabel TextoInicioSesion;
    private javax.swing.JLabel UsuarioLogo;
    private javax.swing.JPasswordField contraseñaU;
    private vista.fondoBlanco fondoBlanco1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField nombreU;
    // End of variables declaration//GEN-END:variables
}
