/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Registro;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import modelo.Producto;

/**
 *
 * @author Yo
 */
public class ListarProducto extends javax.swing.JFrame {

    /**
     * Creates new form ListarProducto
     */
    
    private Registro registro;
    
    public ListarProducto() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        this.registro = new Registro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProducto = new javax.swing.JTable();
        seleccionarCategoria = new javax.swing.JComboBox<>();
        bottonActualizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Regresar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        agregarM = new javax.swing.JMenuItem();
        modificarM = new javax.swing.JMenuItem();
        eliminarM = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Categoria", "Nombre", "Precio", "Cantidad", "Imagen"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaProducto.setRowHeight(70);
        jScrollPane1.setViewportView(tablaProducto);
        if (tablaProducto.getColumnModel().getColumnCount() > 0) {
            tablaProducto.getColumnModel().getColumn(0).setResizable(false);
            tablaProducto.getColumnModel().getColumn(1).setResizable(false);
            tablaProducto.getColumnModel().getColumn(2).setResizable(false);
            tablaProducto.getColumnModel().getColumn(3).setResizable(false);
            tablaProducto.getColumnModel().getColumn(4).setResizable(false);
            tablaProducto.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 590, 400));

        seleccionarCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "General", "Bebida", "Comida" }));
        jPanel1.add(seleccionarCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 100, 160, -1));

        bottonActualizar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        bottonActualizar.setForeground(new java.awt.Color(102, 102, 102));
        bottonActualizar.setText("Actualizar");
        bottonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(bottonActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, 100, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoMetodos.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, -1));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Home.png"))); // NOI18N
        jMenu1.setText("Inicio");

        Regresar.setText("Regresar");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });
        jMenu1.add(Regresar);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/UsuarioLogo.png"))); // NOI18N
        jMenu2.setText("Usuario");

        agregarM.setText("Agregar Productos");
        agregarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarMActionPerformed(evt);
            }
        });
        jMenu2.add(agregarM);

        modificarM.setText("Modificar Productos");
        modificarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarMActionPerformed(evt);
            }
        });
        jMenu2.add(modificarM);

        eliminarM.setText("Eliminar Productos");
        eliminarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarMActionPerformed(evt);
            }
        });
        jMenu2.add(eliminarM);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        this.dispose();
    }//GEN-LAST:event_RegresarActionPerformed

    private void bottonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonActualizarActionPerformed

        String categoria = seleccionarCategoria.getSelectedItem().toString();
        
        
        if ("General".equals(categoria)) {

            registro.actualizarTabla(registro.listarProductos(), (DefaultTableModel) tablaProducto.getModel(), tablaProducto);
            
        } else {

            registro.actualizarTabla(registro.listarProductoCategoria(categoria), (DefaultTableModel) tablaProducto.getModel(), tablaProducto);
        }
        
        
    }//GEN-LAST:event_bottonActualizarActionPerformed

    private void agregarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarMActionPerformed
        AgregarProducto agregarr = new AgregarProducto();
        
        
        agregarr.setVisible(true);
        
        this.dispose();
        
    }//GEN-LAST:event_agregarMActionPerformed

    private void modificarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarMActionPerformed
        ModificarProducto modificarr = new ModificarProducto();
        
        
        modificarr.setVisible(true);
        
        this.dispose();
        
    }//GEN-LAST:event_modificarMActionPerformed

    private void eliminarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarMActionPerformed
        EliminarProducto eliminarr = new EliminarProducto();
        
        
        eliminarr.setVisible(true);
        
        this.dispose();
        
    }//GEN-LAST:event_eliminarMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Regresar;
    private javax.swing.JMenuItem agregarM;
    private javax.swing.JButton bottonActualizar;
    private javax.swing.JMenuItem eliminarM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem modificarM;
    private javax.swing.JComboBox<String> seleccionarCategoria;
    private javax.swing.JTable tablaProducto;
    // End of variables declaration//GEN-END:variables
}
