/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Registro;
import java.awt.Image;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import modelo.Producto;

/**
 *
 * @author Yo
 */
public class ModificarProducto extends javax.swing.JFrame {

    /**
     * Creates new form ModificarProducto
     */
    
    private Registro registro;
    
    
    
    String rutaImagen;
    
    public ModificarProducto() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        this.registro = new Registro();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bottonVerificar = new javax.swing.JButton();
        idModificar = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        textCategoriaA = new javax.swing.JLabel();
        textNombreA = new javax.swing.JLabel();
        textPrecioA = new javax.swing.JLabel();
        textCantidadA = new javax.swing.JLabel();
        textImagenA = new javax.swing.JLabel();
        categoriaActual = new javax.swing.JTextField();
        nombreActual = new javax.swing.JTextField();
        precioActual = new javax.swing.JTextField();
        cantidadActual = new javax.swing.JTextField();
        imagenActual = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        textCategoriaM = new javax.swing.JLabel();
        textNombreM = new javax.swing.JLabel();
        textPrecioM = new javax.swing.JLabel();
        textCantidadM = new javax.swing.JLabel();
        textImagenM = new javax.swing.JLabel();
        nombreModificar = new javax.swing.JTextField();
        precioModificar = new javax.swing.JTextField();
        cantidadModificar = new javax.swing.JTextField();
        imagenModificar = new javax.swing.JLabel();
        categoriaModificar = new javax.swing.JComboBox<>();
        bottonImagen = new javax.swing.JButton();
        bottonModificar = new javax.swing.JButton();
        bottonLimpiar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Regresar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        agregarM = new javax.swing.JMenuItem();
        eliminarM = new javax.swing.JMenuItem();
        listarM = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bottonVerificar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        bottonVerificar.setForeground(new java.awt.Color(255, 51, 51));
        bottonVerificar.setText("Verificar ID");
        bottonVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonVerificarActionPerformed(evt);
            }
        });
        jPanel1.add(bottonVerificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, -1, -1));

        idModificar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idModificarKeyTyped(evt);
            }
        });
        jPanel1.add(idModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 100, 40));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textCategoriaA.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        textCategoriaA.setText("Categoria Actual:");
        jPanel2.add(textCategoriaA, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 45, -1, -1));

        textNombreA.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        textNombreA.setText("Nombre Actual:");
        jPanel2.add(textNombreA, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 118, 100, -1));

        textPrecioA.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        textPrecioA.setText("Precio Actual:");
        jPanel2.add(textPrecioA, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 188, 90, -1));

        textCantidadA.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        textCantidadA.setText("Cantidad Actual:");
        jPanel2.add(textCantidadA, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 264, 110, -1));

        textImagenA.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        textImagenA.setText("Imagen Actual:");
        jPanel2.add(textImagenA, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 350, -1, -1));

        categoriaActual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                categoriaActualKeyTyped(evt);
            }
        });
        jPanel2.add(categoriaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 100, -1));

        nombreActual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreActualKeyTyped(evt);
            }
        });
        jPanel2.add(nombreActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 100, -1));

        precioActual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                precioActualKeyTyped(evt);
            }
        });
        jPanel2.add(precioActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 100, -1));

        cantidadActual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cantidadActualKeyTyped(evt);
            }
        });
        jPanel2.add(cantidadActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 100, -1));
        jPanel2.add(imagenActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 120, 110));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 440, 460));

        jPanel3.setBackground(new java.awt.Color(255, 204, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textCategoriaM.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        textCategoriaM.setText("Categoria Nueva:");
        jPanel3.add(textCategoriaM, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        textNombreM.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        textNombreM.setText("Nombre Nuevo:");
        jPanel3.add(textNombreM, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 100, -1));

        textPrecioM.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        textPrecioM.setText("Precio Nuevo:");
        jPanel3.add(textPrecioM, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 90, -1));

        textCantidadM.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        textCantidadM.setText("Cantidad Nuevo:");
        jPanel3.add(textCantidadM, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 110, -1));

        textImagenM.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        textImagenM.setText("Imagen Nueva:");
        jPanel3.add(textImagenM, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));
        jPanel3.add(nombreModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 100, -1));

        precioModificar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                precioModificarKeyTyped(evt);
            }
        });
        jPanel3.add(precioModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 100, -1));

        cantidadModificar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cantidadModificarKeyTyped(evt);
            }
        });
        jPanel3.add(cantidadModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 100, -1));
        jPanel3.add(imagenModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 120, 110));

        categoriaModificar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Bebida", "Comida" }));
        jPanel3.add(categoriaModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 100, -1));

        bottonImagen.setText("Elegir Imagen");
        bottonImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonImagenActionPerformed(evt);
            }
        });
        jPanel3.add(bottonImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 440, 460));

        bottonModificar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        bottonModificar.setForeground(new java.awt.Color(0, 204, 0));
        bottonModificar.setText("Modificar Producto");
        bottonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonModificarActionPerformed(evt);
            }
        });
        jPanel1.add(bottonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 620, -1, -1));

        bottonLimpiar.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        bottonLimpiar.setForeground(new java.awt.Color(102, 102, 102));
        bottonLimpiar.setText("Limpiar Casillas");
        bottonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottonLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(bottonLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 620, 140, -1));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID Producto a Modificar");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoModificar.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 670));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Home.png"))); // NOI18N
        jMenu1.setText("Inicio");

        Regresar.setText("Regresar");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });
        jMenu1.add(Regresar);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/UsuarioLogo.png"))); // NOI18N
        jMenu2.setText("Usuario");

        agregarM.setText("Agregar Productos");
        agregarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarMActionPerformed(evt);
            }
        });
        jMenu2.add(agregarM);

        eliminarM.setText("Eliminar Productos");
        eliminarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarMActionPerformed(evt);
            }
        });
        jMenu2.add(eliminarM);

        listarM.setText("Listar Productos");
        listarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarMActionPerformed(evt);
            }
        });
        jMenu2.add(listarM);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bottonVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonVerificarActionPerformed

            int idProducto = Integer.parseInt(this.idModificar.getText());
            
            Producto producto = registro.obtenerProductoPorID(idProducto);
        
            if (producto != null) {
                this.nombreActual.setText(producto.getNombreProducto());
                this.precioActual.setText(String.valueOf(producto.getPrecioProducto()));
                this.cantidadActual.setText(String.valueOf(producto.getCantidadProducto()));
                this.categoriaActual.setText(producto.getCategoriaProducto());
                
                ImageIcon imagenOriginal = new ImageIcon(producto.getImagenProducto());
                Image imagenTamaño = imagenOriginal.getImage().getScaledInstance(50, 50, Image.SCALE_SMOOTH);
                this.imagenActual.setIcon(new ImageIcon(imagenTamaño));



            } else {
                JOptionPane.showMessageDialog(null, "Producto no encontrado", "Error", JOptionPane.ERROR_MESSAGE);
            }
        
    }//GEN-LAST:event_bottonVerificarActionPerformed

    private void idModificarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idModificarKeyTyped
        char validar = evt.getKeyChar();

        if(Character.isLetter(validar) || Character.isWhitespace(validar)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_idModificarKeyTyped

    private void bottonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonModificarActionPerformed

        String idText = this.idModificar.getText();
        String categoria = this.categoriaModificar.getSelectedItem().toString();
        String nombre = this.nombreModificar.getText();
        String precioText = this.precioModificar.getText();
        String cantidadText = this.cantidadModificar.getText();
        
        if(!"Seleccionar".equals(categoria) && !nombre.isEmpty() && !precioText.isEmpty() && !cantidadText.isEmpty() && rutaImagen != null){
            
            try{
                
                int id = Integer.parseInt(idText);
                int precio = Integer.parseInt(precioText);
                int cantidad = Integer.parseInt(cantidadText);

                Path path = Paths.get(rutaImagen);
                byte[] img = Files.readAllBytes(path);


                
                if(registro.modificarProducto(new Producto(id,categoria,nombre,precio,cantidad,img))){
                    JOptionPane.showMessageDialog(this, "Producto modificado correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);   
                }
                
            } catch (NumberFormatException | IOException ex) {
                JOptionPane.showMessageDialog(this, "Error al procesar la información", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
        }else{
            JOptionPane.showMessageDialog(this, "Tienes que rellenar todas las casillas", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bottonModificarActionPerformed

    private void precioModificarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precioModificarKeyTyped
        char validar = evt.getKeyChar();

        if(Character.isLetter(validar) || Character.isWhitespace(validar)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_precioModificarKeyTyped

    private void cantidadModificarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadModificarKeyTyped
        char validar = evt.getKeyChar();

        if(Character.isLetter(validar) || Character.isWhitespace(validar)){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_cantidadModificarKeyTyped

    private void bottonImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonImagenActionPerformed

        JFileChooser fileChooser = new JFileChooser();

        FileNameExtensionFilter extensionFilter = new FileNameExtensionFilter("JPG, PNG & GIF", "jpg", "png", "gif");
        fileChooser.setFileFilter(extensionFilter);

        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            rutaImagen = fileChooser.getSelectedFile().getAbsolutePath();
            Image mImagen = new ImageIcon(rutaImagen).getImage();
            ImageIcon mIcono = new ImageIcon(mImagen.getScaledInstance(this.imagenModificar.getWidth(), imagenModificar.getHeight(), 0));
            this.imagenModificar.setIcon(mIcono);
        }
        
        
    }//GEN-LAST:event_bottonImagenActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
       
        
        this.dispose();

        this.idModificar.setText("");
        this.nombreActual.setText("");
        this.nombreModificar.setText("");
        this.precioActual.setText("");
        this.precioModificar.setText("");
        this.cantidadActual.setText("");
        this.cantidadModificar.setText("");
        this.categoriaActual.setText("");
        this.categoriaModificar.setSelectedIndex(0);
        
        this.imagenActual.setIcon(null);
        this.imagenModificar.setIcon(null);
        
    }//GEN-LAST:event_RegresarActionPerformed

    private void bottonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottonLimpiarActionPerformed
        
        this.idModificar.setText("");
        this.nombreActual.setText("");
        this.nombreModificar.setText("");
        this.precioActual.setText("");
        this.precioModificar.setText("");
        this.cantidadActual.setText("");
        this.cantidadModificar.setText("");
        this.categoriaActual.setText("");
        this.categoriaModificar.setSelectedIndex(0);
        
        this.imagenActual.setIcon(null);
        this.imagenModificar.setIcon(null);
    }//GEN-LAST:event_bottonLimpiarActionPerformed

    private void categoriaActualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_categoriaActualKeyTyped
        evt.consume();
    }//GEN-LAST:event_categoriaActualKeyTyped

    private void nombreActualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreActualKeyTyped
        evt.consume();
    }//GEN-LAST:event_nombreActualKeyTyped

    private void precioActualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precioActualKeyTyped
        evt.consume();
    }//GEN-LAST:event_precioActualKeyTyped

    private void cantidadActualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadActualKeyTyped
        evt.consume();
    }//GEN-LAST:event_cantidadActualKeyTyped

    private void agregarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarMActionPerformed
        AgregarProducto agregarr = new AgregarProducto();
        
        
        agregarr.setVisible(true);
        
        this.dispose();
        
        this.idModificar.setText("");
        this.nombreActual.setText("");
        this.nombreModificar.setText("");
        this.precioActual.setText("");
        this.precioModificar.setText("");
        this.cantidadActual.setText("");
        this.cantidadModificar.setText("");
        this.categoriaActual.setText("");
        this.categoriaModificar.setSelectedIndex(0);
        
        this.imagenActual.setIcon(null);
        this.imagenModificar.setIcon(null);
        
    }//GEN-LAST:event_agregarMActionPerformed

    private void eliminarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarMActionPerformed
        EliminarProducto eliminarr = new EliminarProducto();
        
        
        eliminarr.setVisible(true);
        
        this.dispose();
        
        this.idModificar.setText("");
        this.nombreActual.setText("");
        this.nombreModificar.setText("");
        this.precioActual.setText("");
        this.precioModificar.setText("");
        this.cantidadActual.setText("");
        this.cantidadModificar.setText("");
        this.categoriaActual.setText("");
        this.categoriaModificar.setSelectedIndex(0);
        
        this.imagenActual.setIcon(null);
        this.imagenModificar.setIcon(null);
        
    }//GEN-LAST:event_eliminarMActionPerformed

    private void listarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarMActionPerformed
        ListarProducto listarr = new ListarProducto();
        
        
        listarr.setVisible(true);
        
        this.dispose();
        
        this.idModificar.setText("");
        this.nombreActual.setText("");
        this.nombreModificar.setText("");
        this.precioActual.setText("");
        this.precioModificar.setText("");
        this.cantidadActual.setText("");
        this.cantidadModificar.setText("");
        this.categoriaActual.setText("");
        this.categoriaModificar.setSelectedIndex(0);
        
        this.imagenActual.setIcon(null);
        this.imagenModificar.setIcon(null);
        
    }//GEN-LAST:event_listarMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Regresar;
    private javax.swing.JMenuItem agregarM;
    private javax.swing.JButton bottonImagen;
    private javax.swing.JButton bottonLimpiar;
    private javax.swing.JButton bottonModificar;
    private javax.swing.JButton bottonVerificar;
    private javax.swing.JTextField cantidadActual;
    private javax.swing.JTextField cantidadModificar;
    private javax.swing.JTextField categoriaActual;
    private javax.swing.JComboBox<String> categoriaModificar;
    private javax.swing.JMenuItem eliminarM;
    private javax.swing.JTextField idModificar;
    private javax.swing.JLabel imagenActual;
    private javax.swing.JLabel imagenModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JMenuItem listarM;
    private javax.swing.JTextField nombreActual;
    private javax.swing.JTextField nombreModificar;
    private javax.swing.JTextField precioActual;
    private javax.swing.JTextField precioModificar;
    private javax.swing.JLabel textCantidadA;
    private javax.swing.JLabel textCantidadM;
    private javax.swing.JLabel textCategoriaA;
    private javax.swing.JLabel textCategoriaM;
    private javax.swing.JLabel textImagenA;
    private javax.swing.JLabel textImagenM;
    private javax.swing.JLabel textNombreA;
    private javax.swing.JLabel textNombreM;
    private javax.swing.JLabel textPrecioA;
    private javax.swing.JLabel textPrecioM;
    // End of variables declaration//GEN-END:variables
}
